@startuml package_diagram

package core {
    [gr2343.json] 
    [gr2343.core] 
}

package fxui {
    [gr2343.ui] 
}

package "External Libraries" {
    [javafx]
    [fxml]
    [java.net.http]
}

[gr2343.ui] ..> [javafx]
[gr2343.ui] ..> [fxml]
[gr2343.ui] ..> [gr2343.core]
[gr2343.ui] ..> [gr2343.json]
[gr2343.ui] ..> [java.net.http]

@enduml
