@startuml package_diagram
folder CoffeeRating #DDDDDD{
    component core #DDDDDD{
        package gr2343.core #FFFFCC{
            
        }
        package gr2343.json #FFFFCC{ 
            
        }
    }

    component fxui #DDDDDD{
        package gr2343.ui #FFFFCC{
            
        }
    }

    component jackson {

    }

    component resources {
        package fxml{

        }
        package javafx{

        }
    }
}

gr2343.ui ..> gr2343.core
gr2343.ui ..> gr2343.json

gr2343.json ..> jackson
gr2343.ui ..> fxml
@enduml
